version: '3'
services:
  server:
    image: nginx:latest
    ports:
      - '2280:80'
    volumes:
      - ./:/webapp
      - ./resources/docker/server/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./resources/docker/php/php.dockerfile
    volumes:
      - ./:/webapp
    links:
      - db
  db:
    image: mysql:5
    ports:
      - '2236:3306'
    volumes:
      - './resources/docker/db/data:/var/lib/mysql'
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - '2200:8080'
    env_file:
      - .env
